using System.Diagnostics;
using System.Drawing;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using StatusParser.Console.Configuration;
using StatusParser.Console.Models;

namespace StatusParser.Console.Services;

public sealed class ExcelProcessor
{
    // TODO: Сделать конфигурируемым — пока fallback по позиции колонки K (0-based index 10)
    private const int InputCommentColumnIndex = 10; // 0-based index колонки K в Excel
    private const string OutputCommentHeader = "Комментарий";

    private readonly AppConfig _config;
    private readonly ILogger _logger;

    public ExcelProcessor(AppConfig config, ILogger logger)
    {
        _config = config;
        _logger = logger;
    }

    public ProcessResult Run(string outputFileName)
    {
        var totalSw = Stopwatch.StartNew();
        var result = new ProcessResult();
        var allRows = new List<object[]>(10000);

        var inputDir = new DirectoryInfo(_config.ResolvedInputFolder);
        var files = inputDir.GetFiles("*.xlsx").Where(f => !f.Name.StartsWith("~$")).OrderBy(f => f.Name).ToArray();
        _logger.Info($"Found {files.Length} .xlsx files in: {inputDir.FullName}");

        LogConfigSummary();

        var rules = _config.ColumnMappingRules;
        var outputColumnCount = rules.Length;
        var newStatusRules = _config.NewStatusMappingRules;
        var reasonRules = _config.ReasonMappingRules;

        var seqNumberColIndex = FindRuleIndex(r => r.IsAutoGeneratedSequentialNumber);
        var newStatusColIndex = FindRuleIndex(r => r.TargetColumnName == "Статус новый");
        var reasonColIndex = FindRuleIndex(r => r.IsAutoGeneratedFromNewStatus);
        var commentColIndex = FindRuleIndex(r => r.TargetColumnName == OutputCommentHeader);

        var outputPath = Path.Combine(_config.ResolvedOutputFolder, $"{outputFileName}.xlsx");
        result.OutputFilePath = outputPath;

        var existingStartRow = 1;
        var existingLastNumber = 0;

        if (File.Exists(outputPath))
        {
            _logger.Info($"Output file exists: {outputPath}");
            (existingStartRow, existingLastNumber) = GetExistingFileState(outputPath, outputColumnCount);
            _logger.Info($"  Existing data ends at row {existingStartRow - 1}, last Номер={existingLastNumber}");
        }

        var totalDataRows = 0;
        var totalSkippedRows = 0;

        foreach (var file in files)
        {
            _logger.Info(string.Empty);
            _logger.Info($"=== Processing: {file.Name} ===");

            var fileSw = Stopwatch.StartNew();

            try
            {
                using var package = new ExcelPackage(file);
                var worksheet = package.Workbook.Worksheets[0];
                _logger.Info($"  Sheet: '{worksheet.Name}'");

                if (worksheet.Dimension == null)
                {
                    _logger.Warn($"  Worksheet is empty. Skipping.");
                    continue;
                }

                var rowCount = worksheet.Dimension.Rows;
                var colCount = worksheet.Dimension.Columns;
                _logger.Info($"  Size: {rowCount} rows x {colCount} cols");

                var range = worksheet.Cells[1, 1, rowCount, colCount];
                var data = range.Value as object[,];

                if (data == null)
                {
                    _logger.Warn($"  Could not read data. Skipping.");
                    continue;
                }

                var headerIndex = BuildHeaderIndex(data, colCount);

                _logger.Info($"  Headers found ({headerIndex.Count}): {string.Join(", ", headerIndex.Keys)}");

                var f10ColIdx = headerIndex.TryGetValue("F10", out var f10Idx) ? f10Idx : -1;
                _logger.Info($"  F10 column index: {f10ColIdx}");

                // TODO: определять по SourceColumnName из ColumnMappingRules
                var hasCommentHeader = commentColIndex >= 0 && headerIndex.ContainsKey(OutputCommentHeader);

                var sw = Stopwatch.StartNew();
                var fileMatched = 0;
                var fileSkipped = 0;
                var matchCounts = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
                foreach (var rule in newStatusRules)
                    matchCounts[rule.TargetNewStatusValue] = 0;

                for (var r = 1; r < rowCount; r++)
                {
                    var rawNewStatus = GetRawNewStatusValue(data, r, colCount, f10ColIdx);
                    var matchedNewStatus = MatchStatus(rawNewStatus, newStatusRules);

                    if (matchedNewStatus == null)
                    {
                        fileSkipped++;
                        continue;
                    }

                    var outputRow = new object[outputColumnCount];

                    for (var c = 0; c < outputColumnCount; c++)
                    {
                        var rule = rules[c];

                        if (rule.IsAutoGeneratedSequentialNumber)
                            outputRow[c] = existingLastNumber + allRows.Count + 1;
                        else if (rule.IsAutoGeneratedFromNewStatus || c == newStatusColIndex)
                            { /* filled below */ }
                        else if (rule.IsDirectMapping && headerIndex.TryGetValue(rule.SourceColumnName!, out var colIdx))
                            outputRow[c] = data[r, colIdx] ?? string.Empty;
                        else if (rule.IsIndexBased)
                            outputRow[c] = rule.SourceColumnIndex!.Value <= colCount
                                ? (data[r, rule.SourceColumnIndex!.Value] ?? string.Empty)
                                : string.Empty;
                    }

                    if (newStatusColIndex >= 0)
                        outputRow[newStatusColIndex] = matchedNewStatus;

                    if (reasonColIndex >= 0)
                        outputRow[reasonColIndex] = reasonRules
                            .FirstOrDefault(rr => rr.TargetNewStatus == matchedNewStatus)
                            ?.AssignedReason ?? string.Empty;

                    // TODO: fallback по позиции колонки K, если заголовок не найден в файле
                    if (!hasCommentHeader && commentColIndex >= 0 && colCount > InputCommentColumnIndex)
                    {
                        var fallbackVal = data[r, InputCommentColumnIndex]?.ToString()?.Trim();
                        if (!string.IsNullOrEmpty(fallbackVal))
                            outputRow[commentColIndex] = fallbackVal;
                    }

                    allRows.Add(outputRow);
                    fileMatched++;
                    matchCounts[matchedNewStatus]++;

                    if (fileMatched <= 5 || fileMatched % 1000 == 0)
                    {
                        if (fileMatched <= 5)
                        {
                            var raw = rawNewStatus ?? "(empty)";
                            var reason = outputRow[reasonColIndex >= 0 ? reasonColIndex : 0]?.ToString() ?? string.Empty;
                            _logger.Info($"  [+] Row {r+1}: '{raw}' -> '{matchedNewStatus}' | reason: '{reason}'");
                        }
                        else if (fileMatched == 6)
                        {
                            _logger.Info($"  ... (further match details suppressed)");
                        }
                        else if (fileMatched % 1000 == 0)
                        {
                            _logger.Info($"  Progress: {fileMatched} matches in '{file.Name}'...");
                        }
                    }

                    if (fileMatched % 100_000 == 0)
                        _logger.Info($"  *** Hit {fileMatched} matches in '{file.Name}' ***");
                }

                sw.Stop();
                totalDataRows += rowCount - 1;
                totalSkippedRows += fileSkipped;
                result.TotalFiles++;

                _logger.Info(string.Empty);
                _logger.Info($"  --- File summary ---");
                _logger.Info($"  Total rows in file: {rowCount - 1}");
                _logger.Info($"  Matched: {fileMatched}");
                _logger.Info($"  Skipped (no match): {fileSkipped}");
                _logger.Info($"  Time: {sw.Elapsed.TotalSeconds:F2}s");

                foreach (var kv in matchCounts)
                    if (kv.Value > 0)
                        _logger.Info($"    '{kv.Key}': {kv.Value} rows");
            }
            catch (Exception ex)
            {
                _logger.LogException(ex, $"processing '{file.Name}'");
            }
            finally
            {
                fileSw.Stop();
                _logger.Info($"  File elapsed: {fileSw.Elapsed.TotalSeconds:F2}s");
            }
        }

        result.TotalRowsMatched = allRows.Count;

        _logger.Info(string.Empty);
        _logger.Info("========================================");
        _logger.Info($"FINAL TOTALS:");
        _logger.Info($"  Files processed: {result.TotalFiles}");
        _logger.Info($"  Total data rows read: {totalDataRows}");
        _logger.Info($"  Total matched rows: {allRows.Count}");
        _logger.Info($"  Total skipped rows: {totalSkippedRows}");

        if (allRows.Count == 0)
        {
            _logger.Warn("  No rows matched. Output file will be empty.");
        }

        var articleColIndex = FindColumnIndexByTargetName("Артикул");
        var outputRows = articleColIndex >= 0
            ? RemoveDuplicateRows(allRows, articleColIndex, _logger)
            : allRows;

        _logger.Info($"  Writing output: {outputPath}");
        _logger.Info($"  Starting from row {existingStartRow} (header row 1 + {existingStartRow - 1} existing data rows)");
        WriteOutput(outputPath, outputRows, outputColumnCount, existingStartRow);

        totalSw.Stop();
        _logger.Info($"  Total elapsed: {totalSw.Elapsed.TotalSeconds:F2}s");
        _logger.Info("========================================");

        return result;
    }

    private void LogConfigSummary()
    {
        _logger.Info("Configuration:");
        _logger.Info($"  Input:  {_config.ResolvedInputFolder}");
        _logger.Info($"  Output: {_config.ResolvedOutputFolder}");
        _logger.Info($"  Header color: {_config.OutputTableHeaderBackgroundColor}");

        _logger.Info("  Column mappings:");
        foreach (var rule in _config.ColumnMappingRules)
        {
            if (rule.IsAutoGeneratedSequentialNumber)
                _logger.Info($"    [{rule.TargetColumnName}] = auto-number");
            else if (rule.IsAutoGeneratedFromNewStatus)
                _logger.Info($"    [{rule.TargetColumnName}] = derived from new status");
            else if (rule.IsDirectMapping)
                _logger.Info($"    [{rule.TargetColumnName}] <- '{rule.SourceColumnName}' (by name)");
            else if (rule.IsIndexBased)
                _logger.Info($"    [{rule.TargetColumnName}] <- col #{rule.SourceColumnIndex} (by index)");
        }

        _logger.Info("  Status match rules:");
        foreach (var rule in _config.NewStatusMappingRules)
        {
            var patterns = string.Join(", ", rule.SourceValuePatterns.Select(p => $"'{p}'"));
            _logger.Info($"    '{rule.TargetNewStatusValue}' <- [{patterns}]");
        }

        _logger.Info("  Reason rules:");
        foreach (var rule in _config.ReasonMappingRules)
            _logger.Info($"    '{rule.TargetNewStatus}' -> '{rule.AssignedReason}'");
    }

    private static Dictionary<string, int> BuildHeaderIndex(object[,] data, int colCount)
    {
        var map = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
        for (var c = 0; c < colCount; c++)
        {
            var name = data[0, c]?.ToString()?.Trim();
            if (!string.IsNullOrEmpty(name) && !map.ContainsKey(name))
                map[name] = c;
        }
        return map;
    }

    private static string? GetRawNewStatusValue(object[,] data, int rowIdx, int colCount, int f10ColIdx)
    {
        if (f10ColIdx < 0 || f10ColIdx >= colCount)
            return null;

        var maxCol = Math.Min(f10ColIdx + 3, colCount);
        for (var c = f10ColIdx; c < maxCol; c++)
        {
            var val = data[rowIdx, c]?.ToString()?.Trim();
            if (!string.IsNullOrEmpty(val))
                return val;
        }
        return null;
    }

    private static string? MatchStatus(string? sourceValue, NewStatusMappingRule[] rules)
    {
        if (string.IsNullOrWhiteSpace(sourceValue))
            return null;

        foreach (var rule in rules)
            foreach (var pattern in rule.SourceValuePatterns)
                if (string.Equals(sourceValue.Trim(), pattern.Trim(), StringComparison.OrdinalIgnoreCase))
                    return rule.TargetNewStatusValue;

        return null;
    }

    private int FindColumnIndexByTargetName(string targetName)
    {
        for (var i = 0; i < _config.ColumnMappingRules.Length; i++)
            if (string.Equals(_config.ColumnMappingRules[i].TargetColumnName, targetName, StringComparison.OrdinalIgnoreCase))
                return i;
        return -1;
    }

    private static List<object[]> RemoveDuplicateRows(List<object[]> rows, int articleColIndex, ILogger logger)
    {
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var result = new List<object[]>(rows.Count);

        foreach (var row in rows)
        {
            var value = row[articleColIndex]?.ToString()?.Trim() ?? string.Empty;
            if (!string.IsNullOrEmpty(value) && !seen.Add(value))
                continue;

            result.Add(row);
        }

        var removed = rows.Count - result.Count;
        if (removed > 0)
            logger.Info($"  Removed {removed} duplicate rows (by Артикул)");

        return result;
    }

    private int FindRuleIndex(Func<ColumnMappingRule, bool> predicate)
    {
        for (var i = 0; i < _config.ColumnMappingRules.Length; i++)
            if (predicate(_config.ColumnMappingRules[i]))
                return i;
        return -1;
    }

    private (int startRow, int lastNumber) GetExistingFileState(string outputPath, int columnCount)
    {
        try
        {
            using var package = new ExcelPackage(new FileInfo(outputPath));
            var worksheet = package.Workbook.Worksheets[0];

            if (worksheet.Dimension == null)
                return (1, 0);

            var existingRows = worksheet.Dimension.Rows;
            var lastNumber = 0;

            if (existingRows > 1)
            {
                var lastCell = worksheet.Cells[existingRows, 1];
                if (lastCell.Value != null)
                    int.TryParse(lastCell.Value.ToString(), out lastNumber);
            }

            return (existingRows + 1, lastNumber);
        }
        catch
        {
            _logger.Warn($"  Could not read existing file, starting fresh.");
            return (1, 0);
        }
    }

    private void WriteOutput(string outputPath, List<object[]> rows, int columnCount, int startRow)
    {
        var sw = Stopwatch.StartNew();

        try
        {
            var outDir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(outDir) && !Directory.Exists(outDir))
            {
                _logger.Info($"  Creating output directory: {outDir}");
                Directory.CreateDirectory(outDir);
            }

            var isNewFile = !File.Exists(outputPath);
            using var package = isNewFile ? new ExcelPackage() : new ExcelPackage(new FileInfo(outputPath));

            ExcelWorksheet worksheet;
            int dataStartRow;

            if (isNewFile)
            {
                worksheet = package.Workbook.Worksheets.Add("Результат");
                dataStartRow = 2;

                for (var c = 0; c < columnCount; c++)
                    worksheet.Cells[1, c + 1].Value = _config.ColumnMappingRules[c].TargetColumnName;

                var headerRange = worksheet.Cells[1, 1, 1, columnCount];
                headerRange.Style.Font.Bold = true;
                ApplyHeaderColor(headerRange);
            }
            else
            {
                worksheet = package.Workbook.Worksheets[0];
                dataStartRow = startRow;
                _logger.Info($"  Appending to existing file (start row: {dataStartRow})");
            }

            var totalRows = rows.Count;
            if (totalRows > 0)
            {
                _logger.Info($"  Building {totalRows}x{columnCount} data array...");
                var data = new object[totalRows, columnCount];
                for (var i = 0; i < totalRows; i++)
                    for (var c = 0; c < columnCount; c++)
                        data[i, c] = rows[i][c] ?? string.Empty;

                var endRow = dataStartRow + totalRows - 1;
                _logger.Info($"  Writing rows {dataStartRow}..{endRow} to worksheet...");
                worksheet.Cells[dataStartRow, 1, endRow, columnCount].Value = data;
            }

            _logger.Info($"  Saving to disk...");
            package.SaveAs(new FileInfo(outputPath));

            sw.Stop();
            var fileSize = new FileInfo(outputPath).Length / 1024.0;
            _logger.Info($"  File saved ({fileSize:F1} KB, {sw.Elapsed.TotalSeconds:F2}s)");
            _logger.Info("Done.");
        }
        catch (Exception ex)
        {
            _logger.LogException(ex, "writing output file");
            throw;
        }
    }

    private void ApplyHeaderColor(ExcelRange headerRange)
    {
        var colorName = _config.OutputTableHeaderBackgroundColor?.Trim().ToLowerInvariant() ?? "yellow";
        var color = colorName switch
        {
            "yellow" => Color.Yellow,
            "green" => Color.Green,
            "red" => Color.Red,
            "blue" => Color.Blue,
            "cyan" => Color.Cyan,
            "magenta" => Color.Magenta,
            "orange" => Color.Orange,
            "gray" => Color.Gray,
            "lightgray" => Color.LightGray,
            "darkgray" => Color.DarkGray,
            "lightblue" => Color.LightBlue,
            "lightgreen" => Color.LightGreen,
            _ => Color.Yellow
        };

        headerRange.Style.Fill.PatternType = ExcelFillStyle.Solid;
        headerRange.Style.Fill.BackgroundColor.SetColor(color);
    }
}
