using System.Diagnostics;
using System.Drawing;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using StatusParser.Console.Configuration;
using StatusParser.Console.Models;

namespace StatusParser.Console.Services;

public sealed class ExcelProcessor
{
    private readonly AppConfig _config;
    private readonly ILogger _logger;

    public ExcelProcessor(AppConfig config, ILogger logger)
    {
        _config = config;
        _logger = logger;
    }

    public ProcessResult Run(string outputFileName)
    {
        var result = new ProcessResult();
        var allRows = new List<object[]>(10000);

        var inputDir = new DirectoryInfo(_config.ResolvedInputFolder);
        var files = inputDir.GetFiles("*.xlsx").OrderBy(f => f.Name).ToArray();
        _logger.Info($"Found {files.Length} .xlsx files.");

        var rules = _config.ColumnMappingRules;
        var outputColumnCount = rules.Length;
        var newStatusRules = _config.NewStatusMappingRules;
        var reasonRules = _config.ReasonMappingRules;

        var seqNumberColIndex = FindRuleIndex(r => r.IsAutoGeneratedSequentialNumber);
        var newStatusColIndex = FindRuleIndex(r => r.TargetColumnName == "Статус новый");
        var reasonColIndex = FindRuleIndex(r => r.IsAutoGeneratedFromNewStatus);

        foreach (var file in files)
        {
            _logger.Info($"Processing {file.Name}...");

            try
            {
                using var package = new ExcelPackage(file);
                var worksheet = package.Workbook.Worksheets[0];

                if (worksheet.Dimension == null)
                {
                    _logger.Warn($"  Worksheet in '{file.Name}' is empty. Skipping.");
                    continue;
                }

                var rowCount = worksheet.Dimension.Rows;
                var colCount = worksheet.Dimension.Columns;
                _logger.Info($"  Reading {rowCount} rows x {colCount} cols...");

                var range = worksheet.Cells[1, 1, rowCount, colCount];
                var data = range.Value as object[,];

                if (data == null)
                {
                    _logger.Warn($"  Could not read data from '{file.Name}'. Skipping.");
                    continue;
                }

                var headerIndex = BuildHeaderIndex(data, colCount);

                var sw = Stopwatch.StartNew();
                var fileRowCount = 0;

                for (var r = 1; r < rowCount; r++)
                {
                    var outputRow = new object[outputColumnCount];

                    for (var c = 0; c < outputColumnCount; c++)
                    {
                        var rule = rules[c];

                        if (rule.IsAutoGeneratedSequentialNumber)
                            outputRow[c] = result.TotalRowsMatched + fileRowCount + 1;
                        else if (rule.IsAutoGeneratedFromNewStatus || c == newStatusColIndex)
                            { /* filled after status determination */ }
                        else if (rule.IsDirectMapping && headerIndex.TryGetValue(rule.SourceColumnName!, out var colIdx))
                            outputRow[c] = data[r, colIdx] ?? string.Empty;
                        else if (rule.IsIndexBased)
                            outputRow[c] = rule.SourceColumnIndex!.Value <= colCount
                                ? (data[r, rule.SourceColumnIndex!.Value] ?? string.Empty)
                                : string.Empty;
                    }

                    var rawNewStatus = GetRawNewStatusValue(data, r, colCount);
                    var matchedNewStatus = FuzzyMatchStatus(rawNewStatus, newStatusRules);

                    if (matchedNewStatus == null)
                        continue;

                    if (newStatusColIndex >= 0)
                        outputRow[newStatusColIndex] = matchedNewStatus;

                    if (reasonColIndex >= 0)
                        outputRow[reasonColIndex] = reasonRules
                            .FirstOrDefault(rr => rr.TargetNewStatus == matchedNewStatus)
                            ?.AssignedReason ?? string.Empty;

                    allRows.Add(outputRow);
                    fileRowCount++;

                    if (fileRowCount % 100_000 == 0)
                        _logger.Info($"    Progress: {fileRowCount} rows in '{file.Name}'...");
                }

                sw.Stop();
                _logger.Info($"  Rows processed: {rowCount - 1}, output rows: {fileRowCount} ({sw.Elapsed.TotalSeconds:F2}s)");
                result.TotalFiles++;
            }
            catch (Exception ex)
            {
                _logger.LogException(ex, $"processing '{file.Name}'");
            }
        }

        result.TotalRowsMatched = allRows.Count;
        var outputPath = Path.Combine(_config.ResolvedOutputFolder, $"{outputFileName}.xlsx");
        result.OutputFilePath = outputPath;

        _logger.Info($"Writing results ({allRows.Count} rows, {outputColumnCount} cols) to {outputPath}...");
        WriteOutput(outputPath, allRows, outputColumnCount);

        return result;
    }

    private static Dictionary<string, int> BuildHeaderIndex(object[,] data, int colCount)
    {
        var map = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
        for (var c = 0; c < colCount; c++)
        {
            var name = data[0, c]?.ToString()?.Trim();
            if (!string.IsNullOrEmpty(name) && !map.ContainsKey(name))
                map[name] = c;
        }
        return map;
    }

    private static string? GetRawNewStatusValue(object[,] data, int rowIdx, int colCount)
    {
        if (colCount >= 11)
        {
            var val = data[rowIdx, 10]?.ToString()?.Trim();
            if (!string.IsNullOrEmpty(val))
                return val;
        }
        return null;
    }

    private static string? FuzzyMatchStatus(string? sourceValue, NewStatusMappingRule[] rules)
    {
        if (string.IsNullOrWhiteSpace(sourceValue))
            return null;

        var cleaned = sourceValue.Trim();

        foreach (var rule in rules)
            if (string.Equals(cleaned, rule.SourceValuePattern.Trim(), StringComparison.OrdinalIgnoreCase))
                return rule.TargetNewStatusValue;

        return null;
    }

    private int FindRuleIndex(Func<ColumnMappingRule, bool> predicate)
    {
        for (var i = 0; i < _config.ColumnMappingRules.Length; i++)
            if (predicate(_config.ColumnMappingRules[i]))
                return i;
        return -1;
    }

    private void WriteOutput(string outputPath, List<object[]> rows, int columnCount)
    {
        try
        {
            var outDir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(outDir) && !Directory.Exists(outDir))
                Directory.CreateDirectory(outDir);

            if (File.Exists(outputPath))
                File.Delete(outputPath);

            using var package = new ExcelPackage();
            var worksheet = package.Workbook.Worksheets.Add("Результат");

            for (var c = 0; c < columnCount; c++)
                worksheet.Cells[1, c + 1].Value = _config.ColumnMappingRules[c].TargetColumnName;

            var headerRange = worksheet.Cells[1, 1, 1, columnCount];
            headerRange.Style.Font.Bold = true;
            ApplyHeaderColor(headerRange);

            var totalRows = rows.Count;
            if (totalRows > 0)
            {
                var data = new object[totalRows, columnCount];
                for (var i = 0; i < totalRows; i++)
                    for (var c = 0; c < columnCount; c++)
                        data[i, c] = rows[i][c] ?? string.Empty;

                worksheet.Cells[2, 1, totalRows + 1, columnCount].Value = data;
            }

            package.SaveAs(new FileInfo(outputPath));
            _logger.Info("Done.");
        }
        catch (Exception ex)
        {
            _logger.LogException(ex, "writing output file");
            throw;
        }
    }

    private void ApplyHeaderColor(ExcelRange headerRange)
    {
        var colorName = _config.OutputTableHeaderBackgroundColor?.Trim().ToLowerInvariant() ?? "yellow";
        var color = colorName switch
        {
            "yellow" => Color.Yellow,
            "green" => Color.Green,
            "red" => Color.Red,
            "blue" => Color.Blue,
            "cyan" => Color.Cyan,
            "magenta" => Color.Magenta,
            "orange" => Color.Orange,
            "gray" => Color.Gray,
            "lightgray" => Color.LightGray,
            "darkgray" => Color.DarkGray,
            "lightblue" => Color.LightBlue,
            "lightgreen" => Color.LightGreen,
            _ => Color.Yellow
        };

        headerRange.Style.Fill.PatternType = ExcelFillStyle.Solid;
        headerRange.Style.Fill.BackgroundColor.SetColor(color);
    }
}
