using StatusParser.Console.Configuration;

namespace StatusParser.Console.Services;

public sealed class RowMapper
{
    private const int InputCommentColumnIndex = 10;

    private readonly ColumnMappingRule[] _rules;
    private readonly int[] _sourceColIndices;
    private readonly int _sourceColCount;
    private readonly int _newStatusColIndex;
    private readonly int _reasonColIndex;
    private readonly int _commentColIndex;
    private readonly bool _hasCommentHeader;
    private readonly ReasonMappingRule[] _reasonRules;

    public RowMapper(
        ColumnMappingRule[] rules,
        Dictionary<string, int> headerIndex,
        int sourceColCount,
        int newStatusColIndex,
        int reasonColIndex,
        int commentColIndex,
        bool hasCommentHeader,
        ReasonMappingRule[] reasonRules)
    {
        _rules = rules;
        _sourceColCount = sourceColCount;
        _newStatusColIndex = newStatusColIndex;
        _reasonColIndex = reasonColIndex;
        _commentColIndex = commentColIndex;
        _hasCommentHeader = hasCommentHeader;
        _reasonRules = reasonRules;

        _sourceColIndices = new int[rules.Length];
        for (var i = 0; i < rules.Length; i++)
            _sourceColIndices[i] = rules[i].IsDirectMapping && headerIndex.TryGetValue(rules[i].SourceColumnName!, out var idx)
                ? idx
                : -1;
    }

    public object[] Map(object[,] sourceData, int rowIdx, string matchedNewStatus, int sequentialNumber)
    {
        var outputRow = new object[_rules.Length];

        for (var c = 0; c < _rules.Length; c++)
        {
            var rule = _rules[c];
            var colIdx = _sourceColIndices[c];

            if (rule.IsAutoGeneratedSequentialNumber)
                outputRow[c] = sequentialNumber;
            else if (rule.IsAutoGeneratedFromNewStatus || c == _newStatusColIndex)
            {
                /* filled below */
            }
            else if (rule.IsDirectMapping && colIdx >= 0)
                outputRow[c] = sourceData[rowIdx, colIdx] ?? string.Empty;
            else if (rule.IsIndexBased)
                outputRow[c] = rule.SourceColumnIndex!.Value <= _sourceColCount
                    ? (sourceData[rowIdx, rule.SourceColumnIndex!.Value] ?? string.Empty)
                    : string.Empty;
        }

        if (_newStatusColIndex >= 0)
            outputRow[_newStatusColIndex] = matchedNewStatus;

        if (_reasonColIndex >= 0)
            outputRow[_reasonColIndex] = _reasonRules
                .FirstOrDefault(rr => rr.TargetNewStatus == matchedNewStatus)
                ?.AssignedReason ?? string.Empty;

        if (!_hasCommentHeader && _commentColIndex >= 0 && _sourceColCount > InputCommentColumnIndex)
        {
            var fallbackVal = sourceData[rowIdx, InputCommentColumnIndex]?.ToString()?.Trim();
            if (!string.IsNullOrEmpty(fallbackVal))
                outputRow[_commentColIndex] = fallbackVal;
        }

        return outputRow;
    }
}
