using System.Text.Json.Serialization;

namespace StatusParser.Console.Configuration;

public sealed class AppConfig
{
    public string InputFolder { get; init; } = string.Empty;
    public string OutputFolder { get; init; } = string.Empty;
    public string[] InputSourceColumnNames { get; init; } = [];
    public ColumnMappingRule[] ColumnMappingRules { get; init; } = [];
    public NewStatusMappingRule[] NewStatusMappingRules { get; init; } = [];
    public ReasonMappingRule[] ReasonMappingRules { get; init; } = [];
    public string OutputFileName { get; init; } = string.Empty;
    public string OutputFileNameDatePattern { get; init; } = string.Empty;
    public string OutputTableHeaderBackgroundColor { get; init; } = "yellow";

    [JsonIgnore]
    public string ResolvedInputFolder =>
        string.IsNullOrWhiteSpace(InputFolder)
            ? AppDomain.CurrentDomain.BaseDirectory
            : Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, InputFolder));

    [JsonIgnore]
    public string ResolvedOutputFolder =>
        string.IsNullOrWhiteSpace(OutputFolder)
            ? AppDomain.CurrentDomain.BaseDirectory
            : Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, OutputFolder));

    public List<string> Validate()
    {
        var errors = new List<string>();

        if (string.IsNullOrWhiteSpace(InputFolder))
            errors.Add("InputFolder is required.");

        if (ColumnMappingRules.Length == 0)
            errors.Add("At least one ColumnMappingRule is required.");

        if (string.IsNullOrWhiteSpace(OutputFileName))
            errors.Add("OutputFileName is required.");

        return errors;
    }
}

public sealed class ColumnMappingRule
{
    public string TargetColumnName { get; init; } = string.Empty;
    public string? SourceColumnName { get; init; }
    public int? SourceColumnIndex { get; init; }
    public bool IsAutoGeneratedSequentialNumber { get; init; }
    public bool IsAutoGeneratedFromNewStatus { get; init; }

    [JsonIgnore] public bool IsDirectMapping => !string.IsNullOrEmpty(SourceColumnName);
    [JsonIgnore] public bool IsIndexBased => SourceColumnIndex.HasValue;
}

public sealed class NewStatusMappingRule
{
    public string TargetNewStatusValue { get; init; } = string.Empty;
    public string[] SourceValuePatterns { get; init; } = [];
}

public sealed class ReasonMappingRule
{
    public string TargetNewStatus { get; init; } = string.Empty;
    public string AssignedReason { get; init; } = string.Empty;
}
