using System.Diagnostics;
using StatusParser.Console.Configuration;
using StatusParser.Console.Models;
using StatusParser.Console.Services;

namespace StatusParser.Console.Orchestration;

public sealed class WorkflowOrchestrator : IWorkflowOrchestrator
{
    private const string OutputCommentHeader = "Комментарий";

    private readonly AppConfig _config;
    private readonly ILogger _logger;
    private readonly ExcelReader _reader;
    private readonly ExcelWriter _writer;

    public WorkflowOrchestrator(AppConfig config, ILogger logger, ExcelReader reader, ExcelWriter writer)
    {
        _config = config;
        _logger = logger;
        _reader = reader;
        _writer = writer;
    }

    public ProcessResult Run()
    {
        var totalSw = Stopwatch.StartNew();
        var result = new ProcessResult();
        var allRows = new List<object[]>(10000);

        var inputDir = new DirectoryInfo(_config.ResolvedInputFolder);
        var files = inputDir.GetFiles("*.xlsx").Where(f => !f.Name.StartsWith("~$")).OrderBy(f => f.Name).ToArray();
        _logger.Info($"Found {files.Length} .xlsx files in: {inputDir.FullName}");

        LogConfigSummary();

        var rules = _config.ColumnMappingRules;
        var outputColumnCount = rules.Length;
        var newStatusRules = _config.NewStatusMappingRules;
        var reasonRules = _config.ReasonMappingRules;

        var newStatusColIndex = FindRuleIndex(r => r.TargetColumnName == "Статус новый");
        var reasonColIndex = FindRuleIndex(r => r.IsAutoGeneratedFromNewStatus);
        var commentColIndex = FindRuleIndex(r => r.TargetColumnName == OutputCommentHeader);

        var outputPath = BuildOutputFilePath();
        result.OutputFilePath = outputPath;

        var existingStartRow = 1;
        var existingLastNumber = 0;

        if (File.Exists(outputPath))
        {
            _logger.Info($"Output file exists: {outputPath}");
            (existingStartRow, existingLastNumber) = _writer.GetExistingFileState(outputPath, outputColumnCount);
            _logger.Info($"  Existing data ends at row {existingStartRow - 1}, last Номер={existingLastNumber}");
        }

        var totalDataRows = 0;
        var totalSkippedRows = 0;

        foreach (var file in files)
        {
            _logger.Info(string.Empty);
            _logger.Info($"=== Processing: {file.Name} ===");

            var fileSw = Stopwatch.StartNew();

            try
            {
                var sheet = _reader.ReadSheet(file.FullName);
                _logger.Info($"  Sheet: '{sheet.SheetName}'");
                _logger.Info($"  Size: {sheet.RowCount} rows x {sheet.ColumnCount} cols");
                _logger.Info($"  Headers found ({sheet.HeaderIndex.Count}): {string.Join(", ", sheet.HeaderIndex.Keys)}");

                var f10ColIdx = sheet.HeaderIndex.TryGetValue("F10", out var f10Idx) ? f10Idx : -1;
                _logger.Info($"  F10 column index: {f10ColIdx}");

                var hasCommentHeader = commentColIndex >= 0 && sheet.HeaderIndex.ContainsKey(OutputCommentHeader);

                var sw = Stopwatch.StartNew();
                var fileMatched = 0;
                var fileSkipped = 0;
                var matchCounts = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
                foreach (var rule in newStatusRules)
                    matchCounts[rule.TargetNewStatusValue] = 0;

                var mapper = new RowMapper(
                    rules,
                    sheet.HeaderIndex,
                    sheet.ColumnCount,
                    newStatusColIndex,
                    reasonColIndex,
                    commentColIndex,
                    hasCommentHeader,
                    reasonRules
                );

                for (var r = 1; r < sheet.RowCount; r++)
                {
                    var rawNewStatus = ExcelReader.GetRawNewStatusValue(sheet.Data, r, sheet.ColumnCount, f10ColIdx);
                    var matchedNewStatus = StatusMatcher.MatchStatus(rawNewStatus, newStatusRules);

                    if (matchedNewStatus == null)
                    {
                        fileSkipped++;
                        continue;
                    }

                    var seqNumber = existingLastNumber + allRows.Count + 1;
                    var outputRow = mapper.Map(sheet.Data, r, matchedNewStatus, seqNumber);
                    allRows.Add(outputRow);
                    fileMatched++;
                    matchCounts[matchedNewStatus]++;

                    if (fileMatched <= 5 || fileMatched % 1000 == 0)
                    {
                        if (fileMatched <= 5)
                        {
                            var raw = rawNewStatus ?? "(empty)";
                            var reason = outputRow[reasonColIndex >= 0 ? reasonColIndex : 0]?.ToString() ?? string.Empty;
                            _logger.Info($"  [+] Row {r+1}: '{raw}' -> '{matchedNewStatus}' | reason: '{reason}'");
                        }
                        else if (fileMatched == 6)
                        {
                            _logger.Info($"  ... (further match details suppressed)");
                        }
                        else if (fileMatched % 1000 == 0)
                        {
                            _logger.Info($"  Progress: {fileMatched} matches in '{file.Name}'...");
                        }
                    }

                    if (fileMatched % 100_000 == 0)
                        _logger.Info($"  *** Hit {fileMatched} matches in '{file.Name}' ***");
                }

                sw.Stop();
                totalDataRows += sheet.RowCount - 1;
                totalSkippedRows += fileSkipped;
                result.TotalFiles++;

                _logger.Info(string.Empty);
                _logger.Info($"  --- File summary ---");
                _logger.Info($"  Total rows in file: {sheet.RowCount - 1}");
                _logger.Info($"  Matched: {fileMatched}");
                _logger.Info($"  Skipped (no match): {fileSkipped}");
                _logger.Info($"  Time: {sw.Elapsed.TotalSeconds:F2}s");

                foreach (var kv in matchCounts)
                    if (kv.Value > 0)
                        _logger.Info($"    '{kv.Key}': {kv.Value} rows");
            }
            catch (Exception ex)
            {
                _logger.LogException(ex, $"processing '{file.Name}'");
            }
            finally
            {
                fileSw.Stop();
                _logger.Info($"  File elapsed: {fileSw.Elapsed.TotalSeconds:F2}s");
            }
        }

        result.TotalRowsMatched = allRows.Count;

        _logger.Info(string.Empty);
        _logger.Info("========================================");
        _logger.Info($"FINAL TOTALS:");
        _logger.Info($"  Files processed: {result.TotalFiles}");
        _logger.Info($"  Total data rows read: {totalDataRows}");
        _logger.Info($"  Total matched rows: {allRows.Count}");
        _logger.Info($"  Total skipped rows: {totalSkippedRows}");

        if (allRows.Count == 0)
        {
            _logger.Warn("  No rows matched. Output file will be empty.");
        }

        var articleColIndex = DuplicateRemover.FindColumnIndexByTargetName(rules, "Артикул");
        var outputRows = articleColIndex >= 0
            ? DuplicateRemover.RemoveDuplicateRows(allRows, articleColIndex, _logger)
            : allRows;

        _logger.Info($"  Writing output: {outputPath}");
        _logger.Info($"  Starting from row {existingStartRow} (header row 1 + {existingStartRow - 1} existing data rows)");
        _writer.WriteOutput(outputPath, outputRows, outputColumnCount, existingStartRow);

        totalSw.Stop();
        _logger.Info($"  Total elapsed: {totalSw.Elapsed.TotalSeconds:F2}s");
        _logger.Info("========================================");

        return result;
    }

    private string BuildOutputFilePath()
    {
        var baseName = _config.OutputFileName.Trim();
        var pattern = _config.OutputFileNameDatePattern?.Trim();

        var namePart = string.IsNullOrEmpty(pattern)
            ? baseName
            : $"{baseName} {DateTime.Now.ToString(pattern)}";

        var dir = _config.ResolvedOutputFolder;
        Directory.CreateDirectory(dir);

        var candidate = Path.Combine(dir, $"{namePart}.xlsx");
        if (!File.Exists(candidate))
            return candidate;

        for (var counter = 1; ; counter++)
        {
            candidate = Path.Combine(dir, $"{namePart} ({counter}).xlsx");
            if (!File.Exists(candidate))
                return candidate;
        }
    }

    private void LogConfigSummary()
    {
        _logger.Info("Configuration:");
        _logger.Info($"  Input:  {_config.ResolvedInputFolder}");
        _logger.Info($"  Output: {_config.ResolvedOutputFolder}");
        _logger.Info($"  Header color: {_config.OutputTableHeaderBackgroundColor}");

        _logger.Info("  Column mappings:");
        foreach (var rule in _config.ColumnMappingRules)
        {
            if (rule.IsAutoGeneratedSequentialNumber)
                _logger.Info($"    [{rule.TargetColumnName}] = auto-number");
            else if (rule.IsAutoGeneratedFromNewStatus)
                _logger.Info($"    [{rule.TargetColumnName}] = derived from new status");
            else if (rule.IsDirectMapping)
                _logger.Info($"    [{rule.TargetColumnName}] <- '{rule.SourceColumnName}' (by name)");
            else if (rule.IsIndexBased)
                _logger.Info($"    [{rule.TargetColumnName}] <- col #{rule.SourceColumnIndex} (by index)");
        }

        _logger.Info("  Status match rules:");
        foreach (var rule in _config.NewStatusMappingRules)
        {
            var patterns = string.Join(", ", rule.SourceValuePatterns.Select(p => $"'{p}'"));
            _logger.Info($"    '{rule.TargetNewStatusValue}' <- [{patterns}]");
        }

        _logger.Info("  Reason rules:");
        foreach (var rule in _config.ReasonMappingRules)
            _logger.Info($"    '{rule.TargetNewStatus}' -> '{rule.AssignedReason}'");
    }

    private int FindRuleIndex(Func<ColumnMappingRule, bool> predicate)
    {
        for (var i = 0; i < _config.ColumnMappingRules.Length; i++)
            if (predicate(_config.ColumnMappingRules[i]))
                return i;
        return -1;
    }
}
